return {
    ["船"] = {
        { Name = "Polysurface351", Weight = 1 },
        { Name = "Polysurface11", Weight = 1 },
        { Name = "Polysurface121", Weight = 1 },
        { Name = "Polysurface141", Weight = 1 },
        { Name = "Polysurface161", Weight = 1 },
        { Name = "Polysurface181", Weight = 1 },
        { Name = "Polysurface201", Weight = 1 },
        { Name = "Polysurface21", Weight = 1 },
        { Name = "Polysurface31", Weight = 1 },
        { Name = "Polysurface371", Weight = 1 },
        { Name = "Polysurface381", Weight = 1 },
        { Name = "Polysurface41", Weight = 1 },
        { Name = "Polysurface51", Weight = 1 },
        { Name = "对象001", Weight = 1 },
        { Name = "对象002", Weight = 1 },
        { Name = "对象003", Weight = 1 },
        { Name = "对象004", Weight = 1 },
        { Name = "对象005", Weight = 1 },
        { Name = "对象006", Weight = 1 },
        { Name = "对象007", Weight = 1 },
        { Name = "对象008", Weight = 1 },
        { Name = "对象009", Weight = 1 },
        { Name = "对象010", Weight = 1 },
        { Name = "对象011", Weight = 1 },
        { Name = "对象012", Weight = 1 },
        { Name = "对象013", Weight = 1 },
        { Name = "对象014", Weight = 1 },
        { Name = "对象015", Weight = 1 },
        { Name = "对象016", Weight = 1 },
        { Name = "对象017", Weight = 1 },
        { Name = "对象018", Weight = 1 },
        { Name = "对象019", Weight = 1 },
        { Name = "对象020", Weight = 1 },
        { Name = "对象022", Weight = 1 },
        { Name = "对象023", Weight = 1 },
    }
}